//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DB_WForms_3
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.Guid Id { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public System.Guid BooksId { get; set; }
        public System.Guid ShopsId { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual Shop Shop { get; set; }
    }
}
