//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeverMessenger
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public System.Guid Id { get; set; }
        public System.Guid ToLogin { get; set; }
        public System.Guid FromLogin { get; set; }
        public string MessageText { get; set; }
        public byte[] file { get; set; }
    
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
