//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sale
    {
        public System.Guid Id { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<System.DateTime> SaleDate { get; set; }
        public System.Guid RecordsId { get; set; }
    
        public virtual Record Record { get; set; }
    }
}
