--CREATE TABLE Collective
--(
--[Id] UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWID(),
--[Name] NVARCHAR(MAX) NOT NULL CHECK ([Name] <> N'')
--)

--INSERT INTO Collective
--VALUES

--(NEWID(), N'ERIC CLAPTON'),
--(NEWID(), N'SMOKIE'),
--(NEWID(), N'CECE WHITTAKER'),
--(NEWID(), N'BEE GEES'),
--(NEWID(), N'YES'),
--(NEWID(), N'ВИКТОР ЗЕЛЬЧЕНКО'),
--(NEWID(), N'THE HIPPEST SET'),
--(NEWID(), N'TRIUMVIRAT'),
--(NEWID(), N'DAMAGE (5)'),
--(NEWID(), N'LESLIE MANDOKI'),
--(NEWID(), N'EVA (150)'),
--(NEWID(), N'SUN PALACE'),
--(NEWID(), N'EKATERINA BAZHENOVA-YAMASAKI'),
--(NEWID(), N'BYPASS (RU)'),
--(NEWID(), N'SILK SAW'),
--(NEWID(), N'GATILOVE'),
--(NEWID(), N'AUX FIELD'),
--(NEWID(), N'BLENT'),
--(NEWID(), N'MATERIC')


SELECT * FROM Collective