//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EXAM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Record()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public System.Guid CollectiveID { get; set; }
        public System.Guid PublisherID { get; set; }
        public int Number_of_tracks { get; set; }
        public System.Guid GenreID { get; set; }
        public System.DateTime PublishDate { get; set; }
        public double Price { get; set; }
        public double PriceForSale { get; set; }
    
        public virtual Collective Collective { get; set; }
        public virtual Genre Genre { get; set; }
        public virtual Publisher Publisher { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
