//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdoNetModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Matche
    {
        public int Id { get; set; }
        public System.DateTime DateOf { get; set; }
        public int Team1 { get; set; }
        public int Team2 { get; set; }
    }
}
